# Generated by Django 6.0.7 on 2026-07-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation_options',
            field=models.CharField(blank=True, help_text="Comma-separated options, e.g. 'Red, Blue, Black'. Leave blank if this product has no variations.", max_length=255),
        ),
    ]
