# Generated by Django 6.0.7 on 2026-07-15 08:51

import ecommerce.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_avatar_user_birthday_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=ecommerce.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=ecommerce.encryption.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=ecommerce.encryption.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
