# Generated by Django 6.0.7 on 2026-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivered_at_order_rated_at_order_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_checkout_session_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='order',
            name='external_payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='external_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('paymongo', 'GCash / Maya (PayMongo)'), ('paypal', 'PayPal')], default='', max_length=20),
        ),
    ]
