# Generated by Django 6.0.7 on 2026-07-15 08:51

import django.core.validators
import django.db.models.deletion
import ecommerce.encryption
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_stripe_checkout_session_id_and_more'),
        ('store', '0002_product_variation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line',
            field=ecommerce.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=ecommerce.encryption.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=ecommerce.encryption.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=ecommerce.encryption.EncryptedCharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='store.product')),
            ],
        ),
    ]
