# Generated by Django 6.0.7 on 2026-07-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_discount_amount_orderitem_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'To Pay'), ('paid', 'To Ship'), ('shipped', 'To Receive'), ('delivered', 'To Rate'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Payment failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
